//! Generated by tools/proxy.py; do not edit by hand.
//! Naked tail jumps through the load-time System32 import table. Windows
//! resolves and initializes the dependency before any DLL initializer can call
//! these exports. No resolver, allocation, or LoadLibrary runs on the call path.
//! Regenerate: python tools/proxy.py --dll dxgi.dll
//! 20 named exports
#![allow(non_upper_case_globals)]
use core::arch::naked_asm;
pub const REAL: &str = "dxgi.dll";

#[link(name = "defiance_system_proxy")]
extern "system" {
    #[link_name = "__imp_ApplyCompatResolutionQuirking"]
    static SLOT_ApplyCompatResolutionQuirking: *const ();
}
#[unsafe(naked)]
#[allow(non_snake_case)]
#[export_name = "ApplyCompatResolutionQuirking"]
pub unsafe extern "system" fn f_ApplyCompatResolutionQuirking() {
    naked_asm!("jmp qword ptr [rip + {slot}]", slot = sym SLOT_ApplyCompatResolutionQuirking);
}

#[link(name = "defiance_system_proxy")]
extern "system" {
    #[link_name = "__imp_CompatString"]
    static SLOT_CompatString: *const ();
}
#[unsafe(naked)]
#[allow(non_snake_case)]
#[export_name = "CompatString"]
pub unsafe extern "system" fn f_CompatString() {
    naked_asm!("jmp qword ptr [rip + {slot}]", slot = sym SLOT_CompatString);
}

#[link(name = "defiance_system_proxy")]
extern "system" {
    #[link_name = "__imp_CompatValue"]
    static SLOT_CompatValue: *const ();
}
#[unsafe(naked)]
#[allow(non_snake_case)]
#[export_name = "CompatValue"]
pub unsafe extern "system" fn f_CompatValue() {
    naked_asm!("jmp qword ptr [rip + {slot}]", slot = sym SLOT_CompatValue);
}

#[link(name = "defiance_system_proxy")]
extern "system" {
    #[link_name = "__imp_CreateDXGIFactory"]
    static SLOT_CreateDXGIFactory: *const ();
}
#[unsafe(naked)]
#[allow(non_snake_case)]
#[export_name = "CreateDXGIFactory"]
pub unsafe extern "system" fn f_CreateDXGIFactory() {
    naked_asm!("jmp qword ptr [rip + {slot}]", slot = sym SLOT_CreateDXGIFactory);
}

#[link(name = "defiance_system_proxy")]
extern "system" {
    #[link_name = "__imp_CreateDXGIFactory1"]
    static SLOT_CreateDXGIFactory1: *const ();
}
#[unsafe(naked)]
#[allow(non_snake_case)]
#[export_name = "CreateDXGIFactory1"]
pub unsafe extern "system" fn f_CreateDXGIFactory1() {
    naked_asm!("jmp qword ptr [rip + {slot}]", slot = sym SLOT_CreateDXGIFactory1);
}

#[link(name = "defiance_system_proxy")]
extern "system" {
    #[link_name = "__imp_CreateDXGIFactory2"]
    static SLOT_CreateDXGIFactory2: *const ();
}
#[unsafe(naked)]
#[allow(non_snake_case)]
#[export_name = "CreateDXGIFactory2"]
pub unsafe extern "system" fn f_CreateDXGIFactory2() {
    naked_asm!("jmp qword ptr [rip + {slot}]", slot = sym SLOT_CreateDXGIFactory2);
}

#[link(name = "defiance_system_proxy")]
extern "system" {
    #[link_name = "__imp_DXGID3D10CreateDevice"]
    static SLOT_DXGID3D10CreateDevice: *const ();
}
#[unsafe(naked)]
#[allow(non_snake_case)]
#[export_name = "DXGID3D10CreateDevice"]
pub unsafe extern "system" fn f_DXGID3D10CreateDevice() {
    naked_asm!("jmp qword ptr [rip + {slot}]", slot = sym SLOT_DXGID3D10CreateDevice);
}

#[link(name = "defiance_system_proxy")]
extern "system" {
    #[link_name = "__imp_DXGID3D10CreateLayeredDevice"]
    static SLOT_DXGID3D10CreateLayeredDevice: *const ();
}
#[unsafe(naked)]
#[allow(non_snake_case)]
#[export_name = "DXGID3D10CreateLayeredDevice"]
pub unsafe extern "system" fn f_DXGID3D10CreateLayeredDevice() {
    naked_asm!("jmp qword ptr [rip + {slot}]", slot = sym SLOT_DXGID3D10CreateLayeredDevice);
}

#[link(name = "defiance_system_proxy")]
extern "system" {
    #[link_name = "__imp_DXGID3D10GetLayeredDeviceSize"]
    static SLOT_DXGID3D10GetLayeredDeviceSize: *const ();
}
#[unsafe(naked)]
#[allow(non_snake_case)]
#[export_name = "DXGID3D10GetLayeredDeviceSize"]
pub unsafe extern "system" fn f_DXGID3D10GetLayeredDeviceSize() {
    naked_asm!("jmp qword ptr [rip + {slot}]", slot = sym SLOT_DXGID3D10GetLayeredDeviceSize);
}

#[link(name = "defiance_system_proxy")]
extern "system" {
    #[link_name = "__imp_DXGID3D10RegisterLayers"]
    static SLOT_DXGID3D10RegisterLayers: *const ();
}
#[unsafe(naked)]
#[allow(non_snake_case)]
#[export_name = "DXGID3D10RegisterLayers"]
pub unsafe extern "system" fn f_DXGID3D10RegisterLayers() {
    naked_asm!("jmp qword ptr [rip + {slot}]", slot = sym SLOT_DXGID3D10RegisterLayers);
}

#[link(name = "defiance_system_proxy")]
extern "system" {
    #[link_name = "__imp_DXGIDeclareAdapterRemovalSupport"]
    static SLOT_DXGIDeclareAdapterRemovalSupport: *const ();
}
#[unsafe(naked)]
#[allow(non_snake_case)]
#[export_name = "DXGIDeclareAdapterRemovalSupport"]
pub unsafe extern "system" fn f_DXGIDeclareAdapterRemovalSupport() {
    naked_asm!("jmp qword ptr [rip + {slot}]", slot = sym SLOT_DXGIDeclareAdapterRemovalSupport);
}

#[link(name = "defiance_system_proxy")]
extern "system" {
    #[link_name = "__imp_DXGIDisableVBlankVirtualization"]
    static SLOT_DXGIDisableVBlankVirtualization: *const ();
}
#[unsafe(naked)]
#[allow(non_snake_case)]
#[export_name = "DXGIDisableVBlankVirtualization"]
pub unsafe extern "system" fn f_DXGIDisableVBlankVirtualization() {
    naked_asm!("jmp qword ptr [rip + {slot}]", slot = sym SLOT_DXGIDisableVBlankVirtualization);
}

#[link(name = "defiance_system_proxy")]
extern "system" {
    #[link_name = "__imp_DXGIDumpJournal"]
    static SLOT_DXGIDumpJournal: *const ();
}
#[unsafe(naked)]
#[allow(non_snake_case)]
#[export_name = "DXGIDumpJournal"]
pub unsafe extern "system" fn f_DXGIDumpJournal() {
    naked_asm!("jmp qword ptr [rip + {slot}]", slot = sym SLOT_DXGIDumpJournal);
}

#[link(name = "defiance_system_proxy")]
extern "system" {
    #[link_name = "__imp_DXGIGetDebugInterface1"]
    static SLOT_DXGIGetDebugInterface1: *const ();
}
#[unsafe(naked)]
#[allow(non_snake_case)]
#[export_name = "DXGIGetDebugInterface1"]
pub unsafe extern "system" fn f_DXGIGetDebugInterface1() {
    naked_asm!("jmp qword ptr [rip + {slot}]", slot = sym SLOT_DXGIGetDebugInterface1);
}

#[link(name = "defiance_system_proxy")]
extern "system" {
    #[link_name = "__imp_DXGIReportAdapterConfiguration"]
    static SLOT_DXGIReportAdapterConfiguration: *const ();
}
#[unsafe(naked)]
#[allow(non_snake_case)]
#[export_name = "DXGIReportAdapterConfiguration"]
pub unsafe extern "system" fn f_DXGIReportAdapterConfiguration() {
    naked_asm!("jmp qword ptr [rip + {slot}]", slot = sym SLOT_DXGIReportAdapterConfiguration);
}

#[link(name = "defiance_system_proxy")]
extern "system" {
    #[link_name = "__imp_PIXBeginCapture"]
    static SLOT_PIXBeginCapture: *const ();
}
#[unsafe(naked)]
#[allow(non_snake_case)]
#[export_name = "PIXBeginCapture"]
pub unsafe extern "system" fn f_PIXBeginCapture() {
    naked_asm!("jmp qword ptr [rip + {slot}]", slot = sym SLOT_PIXBeginCapture);
}

#[link(name = "defiance_system_proxy")]
extern "system" {
    #[link_name = "__imp_PIXEndCapture"]
    static SLOT_PIXEndCapture: *const ();
}
#[unsafe(naked)]
#[allow(non_snake_case)]
#[export_name = "PIXEndCapture"]
pub unsafe extern "system" fn f_PIXEndCapture() {
    naked_asm!("jmp qword ptr [rip + {slot}]", slot = sym SLOT_PIXEndCapture);
}

#[link(name = "defiance_system_proxy")]
extern "system" {
    #[link_name = "__imp_PIXGetCaptureState"]
    static SLOT_PIXGetCaptureState: *const ();
}
#[unsafe(naked)]
#[allow(non_snake_case)]
#[export_name = "PIXGetCaptureState"]
pub unsafe extern "system" fn f_PIXGetCaptureState() {
    naked_asm!("jmp qword ptr [rip + {slot}]", slot = sym SLOT_PIXGetCaptureState);
}

#[link(name = "defiance_system_proxy")]
extern "system" {
    #[link_name = "__imp_SetAppCompatStringPointer"]
    static SLOT_SetAppCompatStringPointer: *const ();
}
#[unsafe(naked)]
#[allow(non_snake_case)]
#[export_name = "SetAppCompatStringPointer"]
pub unsafe extern "system" fn f_SetAppCompatStringPointer() {
    naked_asm!("jmp qword ptr [rip + {slot}]", slot = sym SLOT_SetAppCompatStringPointer);
}

#[link(name = "defiance_system_proxy")]
extern "system" {
    #[link_name = "__imp_UpdateHMDEmulationStatus"]
    static SLOT_UpdateHMDEmulationStatus: *const ();
}
#[unsafe(naked)]
#[allow(non_snake_case)]
#[export_name = "UpdateHMDEmulationStatus"]
pub unsafe extern "system" fn f_UpdateHMDEmulationStatus() {
    naked_asm!("jmp qword ptr [rip + {slot}]", slot = sym SLOT_UpdateHMDEmulationStatus);
}
