//! Generated by tools/proxy.py; do not edit by hand.
//! Naked tail jumps through slots filled from the real System32 DLL. Only
//! `ANCHOR` is imported at load time, so Windows loads and initializes the real
//! DLL before this one; DllMain then fills every slot with GetProcAddress
//! (`proxy::resolve`) before any other module can call these exports. No
//! resolver, allocation or LoadLibrary runs on the call path. An export this
//! Windows lacks keeps `proxy::missing`, which returns E_NOTIMPL.
//! Regenerate: python tools/proxy.py --dll dxgi.dll
//! 20 named exports
#![allow(non_upper_case_globals)]
use crate::proxy::{missing, Target};
use core::arch::naked_asm;
pub const REAL: &str = "dxgi.dll";
/// Read by build/proxy_imports.rs, which imports only this export.
#[allow(dead_code)]
pub const ANCHOR: &str = "CreateDXGIFactory";

#[link(name = "defiance_system_proxy")]
extern "system" {
    /// The anchor, imported as data: rustc reaches it through its import slot,
    /// which Windows binds at load time, so its address is the real export's
    /// and locates the real module for `proxy::resolve`.
    #[link_name = "CreateDXGIFactory"]
    pub static ANCHOR_EXPORT: u8;
}

static mut SLOT_ApplyCompatResolutionQuirking: Target = missing;
#[unsafe(naked)]
#[allow(non_snake_case)]
#[export_name = "ApplyCompatResolutionQuirking"]
pub unsafe extern "system" fn f_ApplyCompatResolutionQuirking() {
    naked_asm!("jmp qword ptr [rip + {slot}]", slot = sym SLOT_ApplyCompatResolutionQuirking);
}

static mut SLOT_CompatString: Target = missing;
#[unsafe(naked)]
#[allow(non_snake_case)]
#[export_name = "CompatString"]
pub unsafe extern "system" fn f_CompatString() {
    naked_asm!("jmp qword ptr [rip + {slot}]", slot = sym SLOT_CompatString);
}

static mut SLOT_CompatValue: Target = missing;
#[unsafe(naked)]
#[allow(non_snake_case)]
#[export_name = "CompatValue"]
pub unsafe extern "system" fn f_CompatValue() {
    naked_asm!("jmp qword ptr [rip + {slot}]", slot = sym SLOT_CompatValue);
}

static mut SLOT_CreateDXGIFactory: Target = missing;
#[unsafe(naked)]
#[allow(non_snake_case)]
#[export_name = "CreateDXGIFactory"]
pub unsafe extern "system" fn f_CreateDXGIFactory() {
    naked_asm!("jmp qword ptr [rip + {slot}]", slot = sym SLOT_CreateDXGIFactory);
}

static mut SLOT_CreateDXGIFactory1: Target = missing;
#[unsafe(naked)]
#[allow(non_snake_case)]
#[export_name = "CreateDXGIFactory1"]
pub unsafe extern "system" fn f_CreateDXGIFactory1() {
    naked_asm!("jmp qword ptr [rip + {slot}]", slot = sym SLOT_CreateDXGIFactory1);
}

static mut SLOT_CreateDXGIFactory2: Target = missing;
#[unsafe(naked)]
#[allow(non_snake_case)]
#[export_name = "CreateDXGIFactory2"]
pub unsafe extern "system" fn f_CreateDXGIFactory2() {
    naked_asm!("jmp qword ptr [rip + {slot}]", slot = sym SLOT_CreateDXGIFactory2);
}

static mut SLOT_DXGID3D10CreateDevice: Target = missing;
#[unsafe(naked)]
#[allow(non_snake_case)]
#[export_name = "DXGID3D10CreateDevice"]
pub unsafe extern "system" fn f_DXGID3D10CreateDevice() {
    naked_asm!("jmp qword ptr [rip + {slot}]", slot = sym SLOT_DXGID3D10CreateDevice);
}

static mut SLOT_DXGID3D10CreateLayeredDevice: Target = missing;
#[unsafe(naked)]
#[allow(non_snake_case)]
#[export_name = "DXGID3D10CreateLayeredDevice"]
pub unsafe extern "system" fn f_DXGID3D10CreateLayeredDevice() {
    naked_asm!("jmp qword ptr [rip + {slot}]", slot = sym SLOT_DXGID3D10CreateLayeredDevice);
}

static mut SLOT_DXGID3D10GetLayeredDeviceSize: Target = missing;
#[unsafe(naked)]
#[allow(non_snake_case)]
#[export_name = "DXGID3D10GetLayeredDeviceSize"]
pub unsafe extern "system" fn f_DXGID3D10GetLayeredDeviceSize() {
    naked_asm!("jmp qword ptr [rip + {slot}]", slot = sym SLOT_DXGID3D10GetLayeredDeviceSize);
}

static mut SLOT_DXGID3D10RegisterLayers: Target = missing;
#[unsafe(naked)]
#[allow(non_snake_case)]
#[export_name = "DXGID3D10RegisterLayers"]
pub unsafe extern "system" fn f_DXGID3D10RegisterLayers() {
    naked_asm!("jmp qword ptr [rip + {slot}]", slot = sym SLOT_DXGID3D10RegisterLayers);
}

static mut SLOT_DXGIDeclareAdapterRemovalSupport: Target = missing;
#[unsafe(naked)]
#[allow(non_snake_case)]
#[export_name = "DXGIDeclareAdapterRemovalSupport"]
pub unsafe extern "system" fn f_DXGIDeclareAdapterRemovalSupport() {
    naked_asm!("jmp qword ptr [rip + {slot}]", slot = sym SLOT_DXGIDeclareAdapterRemovalSupport);
}

static mut SLOT_DXGIDisableVBlankVirtualization: Target = missing;
#[unsafe(naked)]
#[allow(non_snake_case)]
#[export_name = "DXGIDisableVBlankVirtualization"]
pub unsafe extern "system" fn f_DXGIDisableVBlankVirtualization() {
    naked_asm!("jmp qword ptr [rip + {slot}]", slot = sym SLOT_DXGIDisableVBlankVirtualization);
}

static mut SLOT_DXGIDumpJournal: Target = missing;
#[unsafe(naked)]
#[allow(non_snake_case)]
#[export_name = "DXGIDumpJournal"]
pub unsafe extern "system" fn f_DXGIDumpJournal() {
    naked_asm!("jmp qword ptr [rip + {slot}]", slot = sym SLOT_DXGIDumpJournal);
}

static mut SLOT_DXGIGetDebugInterface1: Target = missing;
#[unsafe(naked)]
#[allow(non_snake_case)]
#[export_name = "DXGIGetDebugInterface1"]
pub unsafe extern "system" fn f_DXGIGetDebugInterface1() {
    naked_asm!("jmp qword ptr [rip + {slot}]", slot = sym SLOT_DXGIGetDebugInterface1);
}

static mut SLOT_DXGIReportAdapterConfiguration: Target = missing;
#[unsafe(naked)]
#[allow(non_snake_case)]
#[export_name = "DXGIReportAdapterConfiguration"]
pub unsafe extern "system" fn f_DXGIReportAdapterConfiguration() {
    naked_asm!("jmp qword ptr [rip + {slot}]", slot = sym SLOT_DXGIReportAdapterConfiguration);
}

static mut SLOT_PIXBeginCapture: Target = missing;
#[unsafe(naked)]
#[allow(non_snake_case)]
#[export_name = "PIXBeginCapture"]
pub unsafe extern "system" fn f_PIXBeginCapture() {
    naked_asm!("jmp qword ptr [rip + {slot}]", slot = sym SLOT_PIXBeginCapture);
}

static mut SLOT_PIXEndCapture: Target = missing;
#[unsafe(naked)]
#[allow(non_snake_case)]
#[export_name = "PIXEndCapture"]
pub unsafe extern "system" fn f_PIXEndCapture() {
    naked_asm!("jmp qword ptr [rip + {slot}]", slot = sym SLOT_PIXEndCapture);
}

static mut SLOT_PIXGetCaptureState: Target = missing;
#[unsafe(naked)]
#[allow(non_snake_case)]
#[export_name = "PIXGetCaptureState"]
pub unsafe extern "system" fn f_PIXGetCaptureState() {
    naked_asm!("jmp qword ptr [rip + {slot}]", slot = sym SLOT_PIXGetCaptureState);
}

static mut SLOT_SetAppCompatStringPointer: Target = missing;
#[unsafe(naked)]
#[allow(non_snake_case)]
#[export_name = "SetAppCompatStringPointer"]
pub unsafe extern "system" fn f_SetAppCompatStringPointer() {
    naked_asm!("jmp qword ptr [rip + {slot}]", slot = sym SLOT_SetAppCompatStringPointer);
}

static mut SLOT_UpdateHMDEmulationStatus: Target = missing;
#[unsafe(naked)]
#[allow(non_snake_case)]
#[export_name = "UpdateHMDEmulationStatus"]
pub unsafe extern "system" fn f_UpdateHMDEmulationStatus() {
    naked_asm!("jmp qword ptr [rip + {slot}]", slot = sym SLOT_UpdateHMDEmulationStatus);
}

/// Every export's NUL-terminated name and slot, for `proxy::resolve`.
///
/// # Safety
/// The slots are written only by `proxy::resolve`, under the loader lock.
pub unsafe fn slots() -> [(&'static [u8], *mut Target); 20] {
    [
        (
            b"ApplyCompatResolutionQuirking\0",
            &raw mut SLOT_ApplyCompatResolutionQuirking,
        ),
        (b"CompatString\0", &raw mut SLOT_CompatString),
        (b"CompatValue\0", &raw mut SLOT_CompatValue),
        (b"CreateDXGIFactory\0", &raw mut SLOT_CreateDXGIFactory),
        (b"CreateDXGIFactory1\0", &raw mut SLOT_CreateDXGIFactory1),
        (b"CreateDXGIFactory2\0", &raw mut SLOT_CreateDXGIFactory2),
        (
            b"DXGID3D10CreateDevice\0",
            &raw mut SLOT_DXGID3D10CreateDevice,
        ),
        (
            b"DXGID3D10CreateLayeredDevice\0",
            &raw mut SLOT_DXGID3D10CreateLayeredDevice,
        ),
        (
            b"DXGID3D10GetLayeredDeviceSize\0",
            &raw mut SLOT_DXGID3D10GetLayeredDeviceSize,
        ),
        (
            b"DXGID3D10RegisterLayers\0",
            &raw mut SLOT_DXGID3D10RegisterLayers,
        ),
        (
            b"DXGIDeclareAdapterRemovalSupport\0",
            &raw mut SLOT_DXGIDeclareAdapterRemovalSupport,
        ),
        (
            b"DXGIDisableVBlankVirtualization\0",
            &raw mut SLOT_DXGIDisableVBlankVirtualization,
        ),
        (b"DXGIDumpJournal\0", &raw mut SLOT_DXGIDumpJournal),
        (
            b"DXGIGetDebugInterface1\0",
            &raw mut SLOT_DXGIGetDebugInterface1,
        ),
        (
            b"DXGIReportAdapterConfiguration\0",
            &raw mut SLOT_DXGIReportAdapterConfiguration,
        ),
        (b"PIXBeginCapture\0", &raw mut SLOT_PIXBeginCapture),
        (b"PIXEndCapture\0", &raw mut SLOT_PIXEndCapture),
        (b"PIXGetCaptureState\0", &raw mut SLOT_PIXGetCaptureState),
        (
            b"SetAppCompatStringPointer\0",
            &raw mut SLOT_SetAppCompatStringPointer,
        ),
        (
            b"UpdateHMDEmulationStatus\0",
            &raw mut SLOT_UpdateHMDEmulationStatus,
        ),
    ]
}
