[package]
name = "defiance-plugin-squad-management-scroll"
version = "1.1.0"
license = "MPL-2.0"
edition = "2021"
[workspace]
[lib]
crate-type = ["cdylib", "rlib"]
[dependencies]
defiance-api = { path = "../../crates/api" }
defiance-feature-sdk = { path = "../../crates/feature-sdk" }
defiance-core = { path = "../../crates/core" }
[build-dependencies]
defiance-build-support = { path = "../../crates/build-support" }
[profile.release]
panic = "abort"
debug = 2
