// Generated by tools/vehicle_arrival_bindings.py; do not hand edit.
use super::Build;
pub(super) const BUILDS: &[Build] = &[
    Build {
        name: "gog-2025-12-23",
        sha: "17ef48350153306e210e14a24b0ad398c56fb99d3d46c88f246df260ade85780",
        update: 0x124be0,
        method_sha: "ad1f04df55ecdf0a1c7fd99283f027f2cf901593af08a512bdddcd55d3c3a1d7",
    },
    Build {
        name: "steam-2025-12-23",
        sha: "d320f848508c45c9f04df235204b5fbc9ffbb1b7f869e4c5a58d80bb2ecc10ed",
        update: 0x124c70,
        method_sha: "0349a48d352f201bcae474d702894454c4e7eded860cfdd817ca907637ff2e2f",
    },
    Build {
        name: "gog-2026-09-14",
        sha: "eb8674f1d16595a3e9cf6a9ec0062735b1184976495d8d6ade36f7e2574e8aab",
        update: 0x12fd30,
        method_sha: "26de9ff85b7c192fed145066c67fa141bbd998ed7f50fedf17672a81931af25a",
    },
    Build {
        name: "steam-2026-09-22",
        sha: "30264904e1d5199b954bafbd7828cf7190930c246d35fa7b94eefa915e8f0c38",
        update: 0x12fdc0,
        method_sha: "06ecaa1bf4e2a850824ff32a0ec74f49960442d6b988722ee4d6f833f988eead",
    },
    Build {
        name: "gog-2026-09-25",
        sha: "1216d627c7288c7db6940168363be582232ed4d3cb860b8b8c8d7489652eca74",
        update: 0x12fd30,
        method_sha: "77a135c54260d6becb5b3892d43df89244099c0e2d4151279d6c185ec8685ff4",
    },
    Build {
        name: "steam-2026-09-25",
        sha: "adb3ad95926036809b4e554b466bef33d4ac7aa5303e59a9e4a940890bc334b5",
        update: 0x12fdc0,
        method_sha: "490882b5b22ebfe7f381f228b1b554565f6afe235aa47f822b647153d2064eed",
    },
];
