[package]
name = "defiance-plugin-selection"
version = "0.5.0"
license = "MPL-2.0"
edition = "2021"
[lib]
name = "defiance_plugin_feature_selection"
crate-type = ["cdylib"]
[dependencies]
defiance-api = { path = "../../crates/api" }
defiance-feature-sdk = { path = "../../crates/feature-sdk" }
[build-dependencies]
defiance-build-support = { path = "../../crates/build-support" }

[features]
default = ["rust-selection"]
rust-selection = []
parity-test = ["rust-selection"]
