"""Resolve exact-build bindings for the moving weapon handoff detour."""
import hashlib
import json
from pathlib import Path
import re

import builds
from capstone.x86 import X86_OP_IMM, X86_OP_MEM, X86_REG_RIP
from pe import Image
from rustfmt import rustfmt

ROOT = Path(__file__).resolve().parents[1]
REFERENCE_STEP = 0x2D8590
REFERENCE_HELPER = 0x2C28F0


def function_pattern(image, rva, length=96):
    raw = bytearray(image.read(rva, length))
    mask = bytearray(b"\1" * len(raw))
    for ins in image.md.disasm(raw, rva):
        relative = ins.group(1) or ins.group(2)
        for op in ins.operands:
            if op.type == X86_OP_MEM and op.mem.base == X86_REG_RIP:
                start = ins.address - rva + ins.disp_offset
                mask[start:start + ins.disp_size] = b"\0" * ins.disp_size
            elif op.type == X86_OP_IMM and relative:
                start = ins.address - rva + ins.imm_offset
                mask[start:start + ins.imm_size] = b"\0" * ins.imm_size
    return re.compile(b"".join(re.escape(bytes([v])) if m else b"." for v, m in zip(raw, mask)), re.DOTALL)


def locate(image, base, parent, helper):
    pattern = function_pattern(base, parent)
    text = next(s for s in image.sections if s[0] == ".text")
    blob = image.read(text[1], text[2])
    matches = list(pattern.finditer(blob))
    if len(matches) != 1:
        raise ValueError(f"{image.path}: weapon-step signature has {len(matches)} matches")
    step = text[1] + matches[0].start()
    fn = image.function_of(step)
    if not fn or fn[0] != step:
        raise ValueError(f"{image.path}: step did not resolve to a .pdata function start")
    helper_pattern = function_pattern(base, helper, 32)
    helper_matches = list(helper_pattern.finditer(blob))
    if len(helper_matches) != 1:
        raise ValueError(f"{image.path}: animation action helper signature has {len(helper_matches)} matches")
    helper_rva = text[1] + helper_matches[0].start()
    return step, helper_rva


def generate():
    by_name = {}
    rows = []
    reference_image = Image(str(builds.build("steam-2026-09-25").require().logic))
    rust = ["// Generated by tools/moving_actions_sync_bindings.py; do not edit.",
            "pub(super) struct Build { pub name: &'static str, pub sha: &'static str, pub step: usize, pub helper: usize, pub step_bytes: &'static [u8], pub helper_bytes: &'static [u8] }",
            "pub(super) const BUILDS: &[Build] = &[" ]
    current = [b for b in builds.supported() if b.date >= "2026-01-01"]
    for build in sorted(current, key=lambda b: len(b.lineage())):
        path = build.require().logic
        image = Image(str(path))
        if build.base is None:
            base, step, helper = reference_image, REFERENCE_STEP, REFERENCE_HELPER
        else:
            base, step, helper = by_name.get(build.base.name,
                                             (reference_image, REFERENCE_STEP, REFERENCE_HELPER))
        step, helper = locate(image, base, step, helper)
        digest = hashlib.sha256(image.data).hexdigest()
        sb, hb = image.read(step, 32), image.read(helper, 16)
        if len(sb) != 32 or len(hb) != 16:
            raise ValueError(f"{path}: truncated code fingerprint")
        by_name[build.name] = (image, step, helper)
        row = dict(name=build.name, sha=digest, step=step, helper=helper,
                   step_bytes=sb.hex(), helper_bytes=hb.hex())
        rows.append(row)
        fmt = lambda data: ", ".join(f"0x{b:02x}" for b in data)
        rust.append(f'    Build {{ name: "{build.name}", sha: "{digest}", step: 0x{step:x}, helper: 0x{helper:x}, step_bytes: &[{fmt(sb)}], helper_bytes: &[{fmt(hb)}] }},')
        print(f"{build.name}: step {step:#x}, action helper {helper:#x}")
    rust.append("];\n")
    target = ROOT / "plugins/moving-actions-sync/src/sites.rs"
    target.write_text("\n".join(rust), encoding="utf-8", newline="\n")
    rustfmt(target)
    out = ROOT / "out/moving-actions-sync-sites.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(rows, indent=2) + "\n", encoding="utf-8", newline="\n")
    return rows


if __name__ == "__main__":
    generate()
