"""Verify and generate moving-action speed-table bindings for supported DLLs.

The compact switch maps action IDs 0x17, 0x18 and 0x2b to selector 1
(zero speed). Selector 3 is the existing posture-dependent speed calculation.
The complete getter and both tables are captured for runtime verification.
"""
import hashlib
import json
from pathlib import Path
import struct

import builds
from pe import Image
from rustfmt import rustfmt

ROOT = Path(__file__).resolve().parents[1]
ACTIONS = (0x17, 0x18, 0x2b)
ANCHOR = bytes.fromhex("4c8b4158418b406c83c0fd83f828")
SPEED_ANCHOR = bytes.fromhex("4883ec28488b415883786c03")


def require(condition, message):
    if not condition:
        raise ValueError(message)


def unique(img, needle):
    offset = img.data.find(needle)
    if offset < 0 or img.data.find(needle, offset + 1) >= 0:
        raise ValueError(f"{img.path}: expected one match for {needle.hex()}")
    rva = img.file_to_rva(offset)
    if img.section_of(rva) != ".text":
        raise ValueError("speed getter anchor is not executable")
    return rva


def locate(img):
    rva = unique(img, ANCHOR)
    instructions = list(img.disasm(rva, rva + 0x2f))
    lookup = next(i for i in instructions if i.mnemonic == "movzx")
    branch = next(i for i in instructions if i.mnemonic == "mov" and "rax*4" in i.op_str)
    action_table = lookup.operands[1].mem.disp
    jump_table = branch.operands[1].mem.disp
    # R9 is the module base synthesized by the preceding LEA.
    lea = next(i for i in instructions if i.mnemonic == "lea")
    require(lea.address + lea.size + lea.operands[1].mem.disp == 0, "R9 is not the module base")
    targets = struct.unpack("<4I", img.read(jump_table, 16))
    require(img.read(targets[1], 4) == bytes.fromhex("0f57c0c3"), "zero-speed branch differs")
    require(img.read(targets[3], 8) == bytes.fromhex("418b507483ea0274"), "posture branch differs")
    require(targets[3] == next(i for i in instructions if i.mnemonic == "ja").operands[0].imm,
            "default action branch differs")
    table = img.read(action_table, 0x29)
    require({i + 3 for i, selector in enumerate(table) if selector == 1} == {4, 7, *ACTIONS},
            "zero-speed action set differs")
    require(set(table) <= {0, 1, 2, 3}, "unexpected action selector")
    offsets = tuple(action_table + action - 3 - rva for action in ACTIONS)
    before = img.read(rva, action_table + len(table) - rva)
    require(all(before[offset] == 1 for offset in offsets), "patch entries do not select zero speed")
    # The exposed speed getter supplies ordinary navigation with the same cap.
    speed_rva = unique(img, SPEED_ANCHOR)
    speed_calls = [i.operands[0].imm for i in img.disasm(speed_rva, speed_rva + 0x52)
                   if i.mnemonic == "call"]
    require(speed_calls == [rva, rva], "navigation getter does not call the verified speed helper")
    return dict(rva=rva, before=before.hex(), offsets=offsets, speed_rva=speed_rva)


def generate():
    rows = []
    lines = ["// Generated by tools/moving_actions_bindings.py; do not hand edit.",
             "use super::Build;", "pub(super) const BUILDS: &[Build] = &["]
    for build in sorted(builds.supported(), key=lambda build: build.name):
        img = Image(build.require().logic)
        row = dict(name=build.name, sha=hashlib.sha256(img.data).hexdigest(), **locate(img))
        rows.append(row)
        before = ", ".join(f"0x{byte:02x}" for byte in bytes.fromhex(row["before"]))
        offsets = ", ".join(f"0x{offset:x}" for offset in row["offsets"])
        lines.extend(["    Build {", f'        name: "{row["name"]}",',
                      f'        sha: "{row["sha"]}",', f'        rva: 0x{row["rva"]:x},',
                      f"        before: &[{before}],", f"        offsets: [{offsets}],", "    },"])
    lines.append("];\n")
    path = ROOT / "plugins/moving-actions/src/sites.rs"
    path.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    rustfmt(path)
    output = ROOT / "out/moving-actions-sites.json"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(rows, indent=2) + "\n", encoding="utf-8", newline="\n")
    return rows


if __name__ == "__main__":
    for row in generate():
        print(f'{row["name"]}: speed getter {row["rva"]:#x}, patch offsets {row["offsets"]}')
