"""Generate hash-guarded vehicle arrival sites from each build's chassis RTTI."""
import hashlib
import json
import struct
import subprocess

import capstone

import builds
from pe import Image
from rtti import Rtti


# Vfunc 48 spans three contiguous .pdata entries. Its fixed instruction
# sequence is verified with only relative call/data displacements normalized.
METHOD_BYTES = 0x14a
METHOD_SHA = "f25608247dcd3554d6c0a064f11b6331d0869b28725313ed05a12fe2c72907fa"


def method(img):
    rtti = Rtti(img)
    cols = next(cols for name, _, cols in rtti.find("BaseTechChassisFacet")
                if name == ".?AVBaseTechChassisFacet@Leonardo@@")
    tables = [vt for col, vts in cols if img.u32(col + 4) == 0 for vt in vts]
    if len(tables) != 1:
        raise ValueError(f"expected one primary chassis vtable, found {tables}")
    rva = img.u64(tables[0] + 0x180) - img.base
    for cls in ("CarChassisFacet", "TankChassisFacet"):
        cols = next(cols for name, _, cols in rtti.find(cls)
                    if name == f".?AV{cls}@Leonardo@@")
        primary = [vt for col, vts in cols if img.u32(col + 4) == 0 for vt in vts]
        if len(primary) != 1 or img.u64(primary[0] + 0x180) != img.base + rva:
            raise ValueError(f"{cls} does not share the vehicle arrival callback")
    code = img.read(rva, METHOD_BYTES)
    normalized = bytearray(code)
    relocations = []
    for ins in img.disasm(rva, rva + METHOD_BYTES):
        if (ins.mnemonic == "call"
                and ins.operands[0].type == capstone.x86.X86_OP_IMM):
            offset, size = ins.imm_offset, ins.imm_size
            target = "direction"
        elif any(op.type == capstone.x86.X86_OP_MEM
                 and op.mem.base == capstone.x86.X86_REG_RIP for op in ins.operands):
            offset, size = ins.disp_offset, ins.disp_size
            target = "one"
            native_constant = ins.address + ins.size + ins.disp
            if img.read(native_constant, 4) != struct.pack("<f", 1.0):
                raise ValueError("the speed-ratio cap is not 1.0")
        else:
            continue
        if size != 4:
            raise ValueError("unexpected relative operand size")
        at = ins.address - rva + offset
        normalized[at:at + size] = bytes(size)
        relocations.append((at, ins.address - rva + ins.size, target))
    if hashlib.sha256(normalized).hexdigest() != METHOD_SHA:
        raise ValueError("vehicle arrival callback differs from the characterized algorithm")
    if [r[2] for r in relocations] != ["direction", "direction", "one"]:
        raise ValueError("unexpected vehicle arrival dependencies")
    return rva, code, relocations


def expected_sha(build):
    if build.layout is not None:
        return json.loads(build.layout.read_text())["logic_sha256"]
    reference = json.loads((builds.ROOT / "tools/variants/reference/logic.json").read_text())
    key = "source_sha256" if build.name == builds.REFERENCE else "verified_sha"
    return reference[key]


def main():
    lines = ["// Generated by tools/vehicle_arrival_bindings.py; do not hand edit.",
             "use super::Build;", "pub(super) const BUILDS: &[Build] = &["]
    for build in builds.supported():
        build.require()
        img = Image(build.logic)
        sha = hashlib.sha256(img.data).hexdigest()
        if sha != expected_sha(build):
            raise ValueError(f"{build.name}: unsupported logic.dll")
        rva, code, _ = method(img)
        lines.extend(["    Build {", f'        name: "{build.name}",',
                      f'        sha: "{sha}",', f"        update: {rva:#x},",
                      f'        method_sha: "{hashlib.sha256(code).hexdigest()}",', "    },"])
    lines.append("];")
    path = builds.ROOT / "plugins/vehicle-arrival/src/sites.rs"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    subprocess.run(["rustfmt", str(path)], check=True)
    print(f"generated {path.relative_to(builds.ROOT)} for {len(builds.supported())} builds")


if __name__ == "__main__":
    main()
