// Generated by tools/ammo_menu_sites.py; do not hand-edit.
use super::{Build, Kind, Offsets, Site};
pub static BUILDS: &[Build] = &[
    Build {
        sha: "f0184b9fe358172c83261419c8ba3d822a0aa6b06ed3cddb2f7aa3ebb9653db4",
        sites: &[
            Site {
                rva: 0x3debc,
                before: &[0x45, 0x8d, 0x44, 0x24, 0x09],
                field: 4,
                width: 1,
                kind: Kind::Count,
            }, // lea r8d, [r12 + 9]
            Site {
                rva: 0x3dec7,
                before: &[0x48, 0x8d, 0x9e, 0xf8, 0x07, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // lea rbx, [rsi + 0x7f8]
            Site {
                rva: 0x3def7,
                before: &[0x4c, 0x89, 0xa6, 0x08, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov qword ptr [rsi + 0x808], r12
            Site {
                rva: 0x3defe,
                before: &[0x4c, 0x89, 0xa6, 0x10, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov qword ptr [rsi + 0x810], r12
            Site {
                rva: 0x3df05,
                before: &[0x4c, 0x89, 0xa6, 0x18, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov qword ptr [rsi + 0x818], r12
            Site {
                rva: 0x3df0c,
                before: &[0x4c, 0x89, 0xa6, 0x20, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov qword ptr [rsi + 0x820], r12
            Site {
                rva: 0x3df13,
                before: &[0x4c, 0x89, 0xa6, 0x28, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov qword ptr [rsi + 0x828], r12
            Site {
                rva: 0x3df1a,
                before: &[0x4c, 0x89, 0xa6, 0x30, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov qword ptr [rsi + 0x830], r12
            Site {
                rva: 0x3e0b5,
                before: &[0x41, 0xbd, 0x02, 0x00, 0x00, 0x00],
                field: 2,
                width: 4,
                kind: Kind::Zero,
            }, // mov r13d, 2
            Site {
                rva: 0x3e135,
                before: &[0x41, 0xbd, 0x03, 0x00, 0x00, 0x00],
                field: 2,
                width: 4,
                kind: Kind::Zero,
            }, // mov r13d, 3
            Site {
                rva: 0x3e1af,
                before: &[0x41, 0xbd, 0x01, 0x00, 0x00, 0x00],
                field: 2,
                width: 4,
                kind: Kind::Zero,
            }, // mov r13d, 1
            Site {
                rva: 0x3e3e6,
                before: &[0x48, 0x81, 0xff, 0x78, 0x06, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Extent,
            }, // cmp rdi, 0x678
            Site {
                rva: 0x3e3fb,
                before: &[0x4d, 0x8d, 0xbc, 0x24, 0x78, 0x06, 0x00, 0x00],
                field: 4,
                width: 4,
                kind: Kind::Extent,
            }, // lea r15, [r12 + 0x678]
            Site {
                rva: 0x3e4a9,
                before: &[0xba, 0x38, 0x08, 0x00, 0x00],
                field: 1,
                width: 4,
                kind: Kind::Shift,
            }, // mov edx, 0x838
            Site {
                rva: 0x3e4e0,
                before: &[0x41, 0xb8, 0x09, 0x00, 0x00, 0x00],
                field: 2,
                width: 4,
                kind: Kind::Count,
            }, // mov r8d, 9
            Site {
                rva: 0x3e557,
                before: &[0x48, 0x8b, 0xb9, 0x28, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov rdi, qword ptr [rcx + 0x828]
            Site {
                rva: 0x3e55e,
                before: &[0x48, 0x8b, 0x99, 0x20, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov rbx, qword ptr [rcx + 0x820]
            Site {
                rva: 0x3e58c,
                before: &[0x48, 0x8b, 0xbe, 0x10, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov rdi, qword ptr [rsi + 0x810]
            Site {
                rva: 0x3e593,
                before: &[0x48, 0x8b, 0x9e, 0x08, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov rbx, qword ptr [rsi + 0x808]
            Site {
                rva: 0x3e5c3,
                before: &[0x4c, 0x8d, 0x93, 0x78, 0x06, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Extent,
            }, // lea r10, [rbx + 0x678]
            Site {
                rva: 0x3e647,
                before: &[0x48, 0x8d, 0x8e, 0x20, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // lea rcx, [rsi + 0x820]
            Site {
                rva: 0x3e653,
                before: &[0x48, 0x8d, 0x8e, 0x08, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // lea rcx, [rsi + 0x808]
            Site {
                rva: 0x3e65f,
                before: &[0x48, 0x8d, 0x8e, 0xf8, 0x07, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // lea rcx, [rsi + 0x7f8]
            Site {
                rva: 0x3e678,
                before: &[0x41, 0xb8, 0x09, 0x00, 0x00, 0x00],
                field: 2,
                width: 4,
                kind: Kind::Count,
            }, // mov r8d, 9
            Site {
                rva: 0x3e712,
                before: &[0x48, 0x8b, 0xb7, 0xf8, 0x07, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov rsi, qword ptr [rdi + 0x7f8]
            Site {
                rva: 0x3e734,
                before: &[0x48, 0x8d, 0x97, 0xf8, 0x07, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // lea rdx, [rdi + 0x7f8]
            Site {
                rva: 0x3e73b,
                before: &[0x48, 0x8d, 0x8f, 0xf8, 0x07, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // lea rcx, [rdi + 0x7f8]
            Site {
                rva: 0x3e776,
                before: &[0x48, 0x8d, 0xb3, 0x78, 0x06, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Extent,
            }, // lea rsi, [rbx + 0x678]
            Site {
                rva: 0x3e77d,
                before: &[0x48, 0x89, 0x87, 0x00, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov qword ptr [rdi + 0x800], rax
            Site {
                rva: 0x3e830,
                before: &[0x48, 0x8d, 0x81, 0xf8, 0x07, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // lea rax, [rcx + 0x7f8]
            Site {
                rva: 0x3ec8c,
                before: &[0x48, 0x81, 0xc1, 0xf8, 0x07, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // add rcx, 0x7f8
            Site {
                rva: 0x3ef9c,
                before: &[0x4c, 0x8b, 0x87, 0xf8, 0x07, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov r8, qword ptr [rdi + 0x7f8]
            Site {
                rva: 0x3eff2,
                before: &[0x48, 0x8d, 0x8f, 0xf8, 0x07, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // lea rcx, [rdi + 0x7f8]
            Site {
                rva: 0x3f0ba,
                before: &[0x83, 0xfb, 0x09],
                field: 2,
                width: 1,
                kind: Kind::Count,
            }, // cmp ebx, 9
            Site {
                rva: 0x3f14b,
                before: &[0xbd, 0x09, 0x00, 0x00, 0x00],
                field: 1,
                width: 4,
                kind: Kind::Count,
            }, // mov ebp, 9
            Site {
                rva: 0x3f8c5,
                before: &[0x48, 0x8d, 0x85, 0x78, 0x06, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Extent,
            }, // lea rax, [rbp + 0x678]
            Site {
                rva: 0x3fa70,
                before: &[0x48, 0x8d, 0x81, 0xf8, 0x07, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // lea rax, [rcx + 0x7f8]
            Site {
                rva: 0x3fd7e,
                before: &[0x48, 0x8b, 0xaf, 0x28, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov rbp, qword ptr [rdi + 0x828]
            Site {
                rva: 0x3fd85,
                before: &[0x48, 0x8b, 0x9f, 0x20, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov rbx, qword ptr [rdi + 0x820]
            Site {
                rva: 0x3fdab,
                before: &[0x48, 0x8b, 0xaf, 0x10, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov rbp, qword ptr [rdi + 0x810]
            Site {
                rva: 0x3fdb2,
                before: &[0x48, 0x8b, 0x9f, 0x08, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov rbx, qword ptr [rdi + 0x808]
            Site {
                rva: 0x4008d,
                before: &[0x4c, 0x8b, 0xb6, 0x28, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov r14, qword ptr [rsi + 0x828]
            Site {
                rva: 0x40094,
                before: &[0x48, 0x8b, 0x9e, 0x20, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov rbx, qword ptr [rsi + 0x820]
            Site {
                rva: 0x40119,
                before: &[0x4c, 0x8b, 0xb6, 0x10, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov r14, qword ptr [rsi + 0x810]
            Site {
                rva: 0x40120,
                before: &[0x48, 0x8b, 0x9e, 0x08, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov rbx, qword ptr [rsi + 0x808]
            Site {
                rva: 0x406d3,
                before: &[0x4c, 0x8d, 0xb1, 0x20, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // lea r14, [rcx + 0x820]
            Site {
                rva: 0x40705,
                before: &[0x48, 0x3b, 0x9e, 0x28, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // cmp rbx, qword ptr [rsi + 0x828]
            Site {
                rva: 0x40801,
                before: &[0x48, 0x8b, 0x9e, 0x28, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov rbx, qword ptr [rsi + 0x828]
            Site {
                rva: 0x408c3,
                before: &[0x4c, 0x8d, 0xb1, 0x08, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // lea r14, [rcx + 0x808]
            Site {
                rva: 0x408f5,
                before: &[0x48, 0x3b, 0x9e, 0x10, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // cmp rbx, qword ptr [rsi + 0x810]
            Site {
                rva: 0x409f1,
                before: &[0x48, 0x8b, 0x9e, 0x10, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov rbx, qword ptr [rsi + 0x810]
            Site {
                rva: 0x34d2c6,
                before: &[0xb9, 0x38, 0x08, 0x00, 0x00],
                field: 1,
                width: 4,
                kind: Kind::Shift,
            }, // mov ecx, 0x838
            Site {
                rva: 0x4b6af9,
                before: &[0xba, 0x38, 0x08, 0x00, 0x00],
                field: 1,
                width: 4,
                kind: Kind::Shift,
            }, // mov edx, 0x838
        ],
        redraw: 0x3ed10,
        redraw_before: &[
            72, 137, 84, 36, 16, 72, 137, 76, 36, 8, 87, 65, 84, 72, 129, 236, 232, 0, 0, 0,
        ],
        layout: 0x2d1920,
        layout_before: &[
            72, 137, 116, 36, 16, 87, 72, 131, 236, 64, 131, 58, 0, 72, 139, 242,
        ],
        combined: &[
            (
                0x3f8a0,
                &[
                    72, 137, 92, 36, 16, 72, 137, 108, 36, 24, 72, 137, 116, 36, 32,
                ],
            ),
            (
                0x3f1d0,
                &[
                    72, 137, 92, 36, 16, 72, 137, 116, 36, 24, 85, 87, 65, 84, 65, 86,
                ],
            ),
            (
                0x3f800,
                &[
                    72, 137, 92, 36, 8, 72, 137, 116, 36, 16, 87, 72, 131, 236, 32,
                ],
            ),
            (
                0x3b540,
                &[
                    72, 137, 92, 36, 8, 87, 72, 131, 236, 32, 72, 139, 185, 136, 0,
                ],
            ),
            (
                0x3b9f0,
                &[
                    72, 137, 92, 36, 16, 72, 137, 108, 36, 24, 72, 137, 116, 36, 32,
                ],
            ),
            (
                0x3bba0,
                &[
                    72, 137, 92, 36, 16, 72, 137, 116, 36, 24, 72, 137, 124, 36, 32,
                ],
            ),
            (
                0x2cb730,
                &[
                    72, 137, 92, 36, 8, 72, 137, 108, 36, 16, 72, 137, 116, 36, 24, 87,
                ],
            ),
            (
                0x2c3380,
                &[
                    72, 137, 92, 36, 24, 72, 137, 116, 36, 32, 85, 87, 65, 86, 72, 141,
                ],
            ),
        ],
        offsets: Offsets {
            roster: 0x3b8,
            gunner_count: 0x130,
            gunner_get: 0x120,
            pool_get: 0x1b8,
            world_player: 0x700,
            ai_set: 0x3e0,
        },
    },
    Build {
        sha: "dc10419f417aed4ecff348b7c96b3c7c574a9a2541f76c5fbc35eb92dbc716d6",
        sites: &[
            Site {
                rva: 0x3debc,
                before: &[0x45, 0x8d, 0x44, 0x24, 0x09],
                field: 4,
                width: 1,
                kind: Kind::Count,
            }, // lea r8d, [r12 + 9]
            Site {
                rva: 0x3dec7,
                before: &[0x48, 0x8d, 0x9e, 0xf8, 0x07, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // lea rbx, [rsi + 0x7f8]
            Site {
                rva: 0x3def7,
                before: &[0x4c, 0x89, 0xa6, 0x08, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov qword ptr [rsi + 0x808], r12
            Site {
                rva: 0x3defe,
                before: &[0x4c, 0x89, 0xa6, 0x10, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov qword ptr [rsi + 0x810], r12
            Site {
                rva: 0x3df05,
                before: &[0x4c, 0x89, 0xa6, 0x18, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov qword ptr [rsi + 0x818], r12
            Site {
                rva: 0x3df0c,
                before: &[0x4c, 0x89, 0xa6, 0x20, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov qword ptr [rsi + 0x820], r12
            Site {
                rva: 0x3df13,
                before: &[0x4c, 0x89, 0xa6, 0x28, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov qword ptr [rsi + 0x828], r12
            Site {
                rva: 0x3df1a,
                before: &[0x4c, 0x89, 0xa6, 0x30, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov qword ptr [rsi + 0x830], r12
            Site {
                rva: 0x3e0b5,
                before: &[0x41, 0xbd, 0x02, 0x00, 0x00, 0x00],
                field: 2,
                width: 4,
                kind: Kind::Zero,
            }, // mov r13d, 2
            Site {
                rva: 0x3e135,
                before: &[0x41, 0xbd, 0x03, 0x00, 0x00, 0x00],
                field: 2,
                width: 4,
                kind: Kind::Zero,
            }, // mov r13d, 3
            Site {
                rva: 0x3e1af,
                before: &[0x41, 0xbd, 0x01, 0x00, 0x00, 0x00],
                field: 2,
                width: 4,
                kind: Kind::Zero,
            }, // mov r13d, 1
            Site {
                rva: 0x3e3e6,
                before: &[0x48, 0x81, 0xff, 0x78, 0x06, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Extent,
            }, // cmp rdi, 0x678
            Site {
                rva: 0x3e3fb,
                before: &[0x4d, 0x8d, 0xbc, 0x24, 0x78, 0x06, 0x00, 0x00],
                field: 4,
                width: 4,
                kind: Kind::Extent,
            }, // lea r15, [r12 + 0x678]
            Site {
                rva: 0x3e4a9,
                before: &[0xba, 0x38, 0x08, 0x00, 0x00],
                field: 1,
                width: 4,
                kind: Kind::Shift,
            }, // mov edx, 0x838
            Site {
                rva: 0x3e4e0,
                before: &[0x41, 0xb8, 0x09, 0x00, 0x00, 0x00],
                field: 2,
                width: 4,
                kind: Kind::Count,
            }, // mov r8d, 9
            Site {
                rva: 0x3e557,
                before: &[0x48, 0x8b, 0xb9, 0x28, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov rdi, qword ptr [rcx + 0x828]
            Site {
                rva: 0x3e55e,
                before: &[0x48, 0x8b, 0x99, 0x20, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov rbx, qword ptr [rcx + 0x820]
            Site {
                rva: 0x3e58c,
                before: &[0x48, 0x8b, 0xbe, 0x10, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov rdi, qword ptr [rsi + 0x810]
            Site {
                rva: 0x3e593,
                before: &[0x48, 0x8b, 0x9e, 0x08, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov rbx, qword ptr [rsi + 0x808]
            Site {
                rva: 0x3e5c3,
                before: &[0x4c, 0x8d, 0x93, 0x78, 0x06, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Extent,
            }, // lea r10, [rbx + 0x678]
            Site {
                rva: 0x3e647,
                before: &[0x48, 0x8d, 0x8e, 0x20, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // lea rcx, [rsi + 0x820]
            Site {
                rva: 0x3e653,
                before: &[0x48, 0x8d, 0x8e, 0x08, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // lea rcx, [rsi + 0x808]
            Site {
                rva: 0x3e65f,
                before: &[0x48, 0x8d, 0x8e, 0xf8, 0x07, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // lea rcx, [rsi + 0x7f8]
            Site {
                rva: 0x3e678,
                before: &[0x41, 0xb8, 0x09, 0x00, 0x00, 0x00],
                field: 2,
                width: 4,
                kind: Kind::Count,
            }, // mov r8d, 9
            Site {
                rva: 0x3e712,
                before: &[0x48, 0x8b, 0xb7, 0xf8, 0x07, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov rsi, qword ptr [rdi + 0x7f8]
            Site {
                rva: 0x3e734,
                before: &[0x48, 0x8d, 0x97, 0xf8, 0x07, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // lea rdx, [rdi + 0x7f8]
            Site {
                rva: 0x3e73b,
                before: &[0x48, 0x8d, 0x8f, 0xf8, 0x07, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // lea rcx, [rdi + 0x7f8]
            Site {
                rva: 0x3e776,
                before: &[0x48, 0x8d, 0xb3, 0x78, 0x06, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Extent,
            }, // lea rsi, [rbx + 0x678]
            Site {
                rva: 0x3e77d,
                before: &[0x48, 0x89, 0x87, 0x00, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov qword ptr [rdi + 0x800], rax
            Site {
                rva: 0x3e830,
                before: &[0x48, 0x8d, 0x81, 0xf8, 0x07, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // lea rax, [rcx + 0x7f8]
            Site {
                rva: 0x3ec8c,
                before: &[0x48, 0x81, 0xc1, 0xf8, 0x07, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // add rcx, 0x7f8
            Site {
                rva: 0x3ef9c,
                before: &[0x4c, 0x8b, 0x87, 0xf8, 0x07, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov r8, qword ptr [rdi + 0x7f8]
            Site {
                rva: 0x3eff2,
                before: &[0x48, 0x8d, 0x8f, 0xf8, 0x07, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // lea rcx, [rdi + 0x7f8]
            Site {
                rva: 0x3f0ba,
                before: &[0x83, 0xfb, 0x09],
                field: 2,
                width: 1,
                kind: Kind::Count,
            }, // cmp ebx, 9
            Site {
                rva: 0x3f14b,
                before: &[0xbd, 0x09, 0x00, 0x00, 0x00],
                field: 1,
                width: 4,
                kind: Kind::Count,
            }, // mov ebp, 9
            Site {
                rva: 0x3f8c5,
                before: &[0x48, 0x8d, 0x85, 0x78, 0x06, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Extent,
            }, // lea rax, [rbp + 0x678]
            Site {
                rva: 0x3fa70,
                before: &[0x48, 0x8d, 0x81, 0xf8, 0x07, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // lea rax, [rcx + 0x7f8]
            Site {
                rva: 0x3fd7e,
                before: &[0x48, 0x8b, 0xaf, 0x28, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov rbp, qword ptr [rdi + 0x828]
            Site {
                rva: 0x3fd85,
                before: &[0x48, 0x8b, 0x9f, 0x20, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov rbx, qword ptr [rdi + 0x820]
            Site {
                rva: 0x3fdab,
                before: &[0x48, 0x8b, 0xaf, 0x10, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov rbp, qword ptr [rdi + 0x810]
            Site {
                rva: 0x3fdb2,
                before: &[0x48, 0x8b, 0x9f, 0x08, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov rbx, qword ptr [rdi + 0x808]
            Site {
                rva: 0x4008d,
                before: &[0x4c, 0x8b, 0xb6, 0x28, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov r14, qword ptr [rsi + 0x828]
            Site {
                rva: 0x40094,
                before: &[0x48, 0x8b, 0x9e, 0x20, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov rbx, qword ptr [rsi + 0x820]
            Site {
                rva: 0x40119,
                before: &[0x4c, 0x8b, 0xb6, 0x10, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov r14, qword ptr [rsi + 0x810]
            Site {
                rva: 0x40120,
                before: &[0x48, 0x8b, 0x9e, 0x08, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov rbx, qword ptr [rsi + 0x808]
            Site {
                rva: 0x406d3,
                before: &[0x4c, 0x8d, 0xb1, 0x20, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // lea r14, [rcx + 0x820]
            Site {
                rva: 0x40705,
                before: &[0x48, 0x3b, 0x9e, 0x28, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // cmp rbx, qword ptr [rsi + 0x828]
            Site {
                rva: 0x40801,
                before: &[0x48, 0x8b, 0x9e, 0x28, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov rbx, qword ptr [rsi + 0x828]
            Site {
                rva: 0x408c3,
                before: &[0x4c, 0x8d, 0xb1, 0x08, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // lea r14, [rcx + 0x808]
            Site {
                rva: 0x408f5,
                before: &[0x48, 0x3b, 0x9e, 0x10, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // cmp rbx, qword ptr [rsi + 0x810]
            Site {
                rva: 0x409f1,
                before: &[0x48, 0x8b, 0x9e, 0x10, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov rbx, qword ptr [rsi + 0x810]
            Site {
                rva: 0x353776,
                before: &[0xb9, 0x38, 0x08, 0x00, 0x00],
                field: 1,
                width: 4,
                kind: Kind::Shift,
            }, // mov ecx, 0x838
            Site {
                rva: 0x4bd3d9,
                before: &[0xba, 0x38, 0x08, 0x00, 0x00],
                field: 1,
                width: 4,
                kind: Kind::Shift,
            }, // mov edx, 0x838
        ],
        redraw: 0x3ed10,
        redraw_before: &[
            72, 137, 84, 36, 16, 72, 137, 76, 36, 8, 87, 65, 84, 72, 129, 236, 232, 0, 0, 0,
        ],
        layout: 0x2d6cb0,
        layout_before: &[
            72, 137, 116, 36, 16, 87, 72, 131, 236, 64, 131, 58, 0, 72, 139, 242,
        ],
        combined: &[
            (
                0x3f8a0,
                &[
                    72, 137, 92, 36, 16, 72, 137, 108, 36, 24, 72, 137, 116, 36, 32,
                ],
            ),
            (
                0x3f1d0,
                &[
                    72, 137, 92, 36, 16, 72, 137, 116, 36, 24, 85, 87, 65, 84, 65, 86,
                ],
            ),
            (
                0x3f800,
                &[
                    72, 137, 92, 36, 8, 72, 137, 116, 36, 16, 87, 72, 131, 236, 32,
                ],
            ),
            (
                0x3b540,
                &[
                    72, 137, 92, 36, 8, 87, 72, 131, 236, 32, 72, 139, 185, 136, 0,
                ],
            ),
            (
                0x3b9f0,
                &[
                    72, 137, 92, 36, 16, 72, 137, 108, 36, 24, 72, 137, 116, 36, 32,
                ],
            ),
            (
                0x3bba0,
                &[
                    72, 137, 92, 36, 16, 72, 137, 116, 36, 24, 72, 137, 124, 36, 32,
                ],
            ),
            (
                0x2d0ac0,
                &[
                    72, 137, 92, 36, 8, 72, 137, 108, 36, 16, 72, 137, 116, 36, 24, 87,
                ],
            ),
            (
                0x2c8710,
                &[
                    72, 137, 92, 36, 24, 72, 137, 116, 36, 32, 85, 87, 65, 86, 72, 141,
                ],
            ),
        ],
        offsets: Offsets {
            roster: 0x3b8,
            gunner_count: 0x130,
            gunner_get: 0x120,
            pool_get: 0x1b8,
            world_player: 0x700,
            ai_set: 0x3e0,
        },
    },
    Build {
        sha: "bc2af42369f9f6fe70e206ae4846f8f0e46ac01cca9a325c8159ee04a9b5e405",
        sites: &[
            Site {
                rva: 0x3e05c,
                before: &[0x45, 0x8d, 0x44, 0x24, 0x09],
                field: 4,
                width: 1,
                kind: Kind::Count,
            }, // lea r8d, [r12 + 9]
            Site {
                rva: 0x3e067,
                before: &[0x48, 0x8d, 0x9e, 0xf8, 0x07, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // lea rbx, [rsi + 0x7f8]
            Site {
                rva: 0x3e097,
                before: &[0x4c, 0x89, 0xa6, 0x08, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov qword ptr [rsi + 0x808], r12
            Site {
                rva: 0x3e09e,
                before: &[0x4c, 0x89, 0xa6, 0x10, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov qword ptr [rsi + 0x810], r12
            Site {
                rva: 0x3e0a5,
                before: &[0x4c, 0x89, 0xa6, 0x18, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov qword ptr [rsi + 0x818], r12
            Site {
                rva: 0x3e0ac,
                before: &[0x4c, 0x89, 0xa6, 0x20, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov qword ptr [rsi + 0x820], r12
            Site {
                rva: 0x3e0b3,
                before: &[0x4c, 0x89, 0xa6, 0x28, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov qword ptr [rsi + 0x828], r12
            Site {
                rva: 0x3e0ba,
                before: &[0x4c, 0x89, 0xa6, 0x30, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov qword ptr [rsi + 0x830], r12
            Site {
                rva: 0x3e255,
                before: &[0x41, 0xbd, 0x02, 0x00, 0x00, 0x00],
                field: 2,
                width: 4,
                kind: Kind::Zero,
            }, // mov r13d, 2
            Site {
                rva: 0x3e2d5,
                before: &[0x41, 0xbd, 0x03, 0x00, 0x00, 0x00],
                field: 2,
                width: 4,
                kind: Kind::Zero,
            }, // mov r13d, 3
            Site {
                rva: 0x3e34f,
                before: &[0x41, 0xbd, 0x01, 0x00, 0x00, 0x00],
                field: 2,
                width: 4,
                kind: Kind::Zero,
            }, // mov r13d, 1
            Site {
                rva: 0x3e586,
                before: &[0x48, 0x81, 0xff, 0x78, 0x06, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Extent,
            }, // cmp rdi, 0x678
            Site {
                rva: 0x3e59b,
                before: &[0x4d, 0x8d, 0xbc, 0x24, 0x78, 0x06, 0x00, 0x00],
                field: 4,
                width: 4,
                kind: Kind::Extent,
            }, // lea r15, [r12 + 0x678]
            Site {
                rva: 0x3e649,
                before: &[0xba, 0x38, 0x08, 0x00, 0x00],
                field: 1,
                width: 4,
                kind: Kind::Shift,
            }, // mov edx, 0x838
            Site {
                rva: 0x3e680,
                before: &[0x41, 0xb8, 0x09, 0x00, 0x00, 0x00],
                field: 2,
                width: 4,
                kind: Kind::Count,
            }, // mov r8d, 9
            Site {
                rva: 0x3e6f7,
                before: &[0x48, 0x8b, 0xb9, 0x28, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov rdi, qword ptr [rcx + 0x828]
            Site {
                rva: 0x3e6fe,
                before: &[0x48, 0x8b, 0x99, 0x20, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov rbx, qword ptr [rcx + 0x820]
            Site {
                rva: 0x3e72c,
                before: &[0x48, 0x8b, 0xbe, 0x10, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov rdi, qword ptr [rsi + 0x810]
            Site {
                rva: 0x3e733,
                before: &[0x48, 0x8b, 0x9e, 0x08, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov rbx, qword ptr [rsi + 0x808]
            Site {
                rva: 0x3e763,
                before: &[0x4c, 0x8d, 0x93, 0x78, 0x06, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Extent,
            }, // lea r10, [rbx + 0x678]
            Site {
                rva: 0x3e7e7,
                before: &[0x48, 0x8d, 0x8e, 0x20, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // lea rcx, [rsi + 0x820]
            Site {
                rva: 0x3e7f3,
                before: &[0x48, 0x8d, 0x8e, 0x08, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // lea rcx, [rsi + 0x808]
            Site {
                rva: 0x3e7ff,
                before: &[0x48, 0x8d, 0x8e, 0xf8, 0x07, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // lea rcx, [rsi + 0x7f8]
            Site {
                rva: 0x3e818,
                before: &[0x41, 0xb8, 0x09, 0x00, 0x00, 0x00],
                field: 2,
                width: 4,
                kind: Kind::Count,
            }, // mov r8d, 9
            Site {
                rva: 0x3e8b2,
                before: &[0x48, 0x8b, 0xb7, 0xf8, 0x07, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov rsi, qword ptr [rdi + 0x7f8]
            Site {
                rva: 0x3e8d4,
                before: &[0x48, 0x8d, 0x97, 0xf8, 0x07, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // lea rdx, [rdi + 0x7f8]
            Site {
                rva: 0x3e8db,
                before: &[0x48, 0x8d, 0x8f, 0xf8, 0x07, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // lea rcx, [rdi + 0x7f8]
            Site {
                rva: 0x3e916,
                before: &[0x48, 0x8d, 0xb3, 0x78, 0x06, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Extent,
            }, // lea rsi, [rbx + 0x678]
            Site {
                rva: 0x3e91d,
                before: &[0x48, 0x89, 0x87, 0x00, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov qword ptr [rdi + 0x800], rax
            Site {
                rva: 0x3e9d0,
                before: &[0x48, 0x8d, 0x81, 0xf8, 0x07, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // lea rax, [rcx + 0x7f8]
            Site {
                rva: 0x3ee2c,
                before: &[0x48, 0x81, 0xc1, 0xf8, 0x07, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // add rcx, 0x7f8
            Site {
                rva: 0x3f13c,
                before: &[0x4c, 0x8b, 0x87, 0xf8, 0x07, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov r8, qword ptr [rdi + 0x7f8]
            Site {
                rva: 0x3f192,
                before: &[0x48, 0x8d, 0x8f, 0xf8, 0x07, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // lea rcx, [rdi + 0x7f8]
            Site {
                rva: 0x3f25a,
                before: &[0x83, 0xfb, 0x09],
                field: 2,
                width: 1,
                kind: Kind::Count,
            }, // cmp ebx, 9
            Site {
                rva: 0x3f2eb,
                before: &[0xbd, 0x09, 0x00, 0x00, 0x00],
                field: 1,
                width: 4,
                kind: Kind::Count,
            }, // mov ebp, 9
            Site {
                rva: 0x3fa65,
                before: &[0x48, 0x8d, 0x85, 0x78, 0x06, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Extent,
            }, // lea rax, [rbp + 0x678]
            Site {
                rva: 0x3fc10,
                before: &[0x48, 0x8d, 0x81, 0xf8, 0x07, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // lea rax, [rcx + 0x7f8]
            Site {
                rva: 0x3ff1e,
                before: &[0x48, 0x8b, 0xaf, 0x28, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov rbp, qword ptr [rdi + 0x828]
            Site {
                rva: 0x3ff25,
                before: &[0x48, 0x8b, 0x9f, 0x20, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov rbx, qword ptr [rdi + 0x820]
            Site {
                rva: 0x3ff4b,
                before: &[0x48, 0x8b, 0xaf, 0x10, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov rbp, qword ptr [rdi + 0x810]
            Site {
                rva: 0x3ff52,
                before: &[0x48, 0x8b, 0x9f, 0x08, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov rbx, qword ptr [rdi + 0x808]
            Site {
                rva: 0x4022d,
                before: &[0x4c, 0x8b, 0xb6, 0x28, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov r14, qword ptr [rsi + 0x828]
            Site {
                rva: 0x40234,
                before: &[0x48, 0x8b, 0x9e, 0x20, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov rbx, qword ptr [rsi + 0x820]
            Site {
                rva: 0x402b9,
                before: &[0x4c, 0x8b, 0xb6, 0x10, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov r14, qword ptr [rsi + 0x810]
            Site {
                rva: 0x402c0,
                before: &[0x48, 0x8b, 0x9e, 0x08, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov rbx, qword ptr [rsi + 0x808]
            Site {
                rva: 0x40873,
                before: &[0x4c, 0x8d, 0xb1, 0x20, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // lea r14, [rcx + 0x820]
            Site {
                rva: 0x408a5,
                before: &[0x48, 0x3b, 0x9e, 0x28, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // cmp rbx, qword ptr [rsi + 0x828]
            Site {
                rva: 0x409a1,
                before: &[0x48, 0x8b, 0x9e, 0x28, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov rbx, qword ptr [rsi + 0x828]
            Site {
                rva: 0x40a63,
                before: &[0x4c, 0x8d, 0xb1, 0x08, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // lea r14, [rcx + 0x808]
            Site {
                rva: 0x40a95,
                before: &[0x48, 0x3b, 0x9e, 0x10, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // cmp rbx, qword ptr [rsi + 0x810]
            Site {
                rva: 0x40b91,
                before: &[0x48, 0x8b, 0x9e, 0x10, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov rbx, qword ptr [rsi + 0x810]
            Site {
                rva: 0x34f4a6,
                before: &[0xb9, 0x38, 0x08, 0x00, 0x00],
                field: 1,
                width: 4,
                kind: Kind::Shift,
            }, // mov ecx, 0x838
            Site {
                rva: 0x4b8ee9,
                before: &[0xba, 0x38, 0x08, 0x00, 0x00],
                field: 1,
                width: 4,
                kind: Kind::Shift,
            }, // mov edx, 0x838
        ],
        redraw: 0x3eeb0,
        redraw_before: &[
            72, 137, 84, 36, 16, 72, 137, 76, 36, 8, 87, 65, 84, 72, 129, 236, 232, 0, 0, 0,
        ],
        layout: 0x2d3ab0,
        layout_before: &[
            72, 137, 116, 36, 16, 87, 72, 131, 236, 64, 131, 58, 0, 72, 139, 242,
        ],
        combined: &[
            (
                0x3fa40,
                &[
                    72, 137, 92, 36, 16, 72, 137, 108, 36, 24, 72, 137, 116, 36, 32,
                ],
            ),
            (
                0x3f370,
                &[
                    72, 137, 92, 36, 16, 72, 137, 116, 36, 24, 85, 87, 65, 84, 65, 86,
                ],
            ),
            (
                0x3f9a0,
                &[
                    72, 137, 92, 36, 8, 72, 137, 116, 36, 16, 87, 72, 131, 236, 32,
                ],
            ),
            (
                0x3b6e0,
                &[
                    72, 137, 92, 36, 8, 87, 72, 131, 236, 32, 72, 139, 185, 136, 0,
                ],
            ),
            (
                0x3bb90,
                &[
                    72, 137, 92, 36, 16, 72, 137, 108, 36, 24, 72, 137, 116, 36, 32,
                ],
            ),
            (
                0x3bd40,
                &[
                    72, 137, 92, 36, 16, 72, 137, 116, 36, 24, 72, 137, 124, 36, 32,
                ],
            ),
            (
                0x2cd8c0,
                &[
                    72, 137, 92, 36, 8, 72, 137, 108, 36, 16, 72, 137, 116, 36, 24, 87,
                ],
            ),
            (
                0x2c5400,
                &[
                    72, 137, 92, 36, 24, 72, 137, 116, 36, 32, 85, 87, 65, 86, 72, 141,
                ],
            ),
        ],
        offsets: Offsets {
            roster: 0x3d0,
            gunner_count: 0x140,
            gunner_get: 0x130,
            pool_get: 0x1c8,
            world_player: 0x708,
            ai_set: 0x3f8,
        },
    },
    Build {
        sha: "d926a213731d73bac8ccc56b50e2b4292fe8613c7a9bb7c8b9fc9132c122ed25",
        sites: &[
            Site {
                rva: 0x3e05c,
                before: &[0x45, 0x8d, 0x44, 0x24, 0x09],
                field: 4,
                width: 1,
                kind: Kind::Count,
            }, // lea r8d, [r12 + 9]
            Site {
                rva: 0x3e067,
                before: &[0x48, 0x8d, 0x9e, 0xf8, 0x07, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // lea rbx, [rsi + 0x7f8]
            Site {
                rva: 0x3e097,
                before: &[0x4c, 0x89, 0xa6, 0x08, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov qword ptr [rsi + 0x808], r12
            Site {
                rva: 0x3e09e,
                before: &[0x4c, 0x89, 0xa6, 0x10, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov qword ptr [rsi + 0x810], r12
            Site {
                rva: 0x3e0a5,
                before: &[0x4c, 0x89, 0xa6, 0x18, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov qword ptr [rsi + 0x818], r12
            Site {
                rva: 0x3e0ac,
                before: &[0x4c, 0x89, 0xa6, 0x20, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov qword ptr [rsi + 0x820], r12
            Site {
                rva: 0x3e0b3,
                before: &[0x4c, 0x89, 0xa6, 0x28, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov qword ptr [rsi + 0x828], r12
            Site {
                rva: 0x3e0ba,
                before: &[0x4c, 0x89, 0xa6, 0x30, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov qword ptr [rsi + 0x830], r12
            Site {
                rva: 0x3e255,
                before: &[0x41, 0xbd, 0x02, 0x00, 0x00, 0x00],
                field: 2,
                width: 4,
                kind: Kind::Zero,
            }, // mov r13d, 2
            Site {
                rva: 0x3e2d5,
                before: &[0x41, 0xbd, 0x03, 0x00, 0x00, 0x00],
                field: 2,
                width: 4,
                kind: Kind::Zero,
            }, // mov r13d, 3
            Site {
                rva: 0x3e34f,
                before: &[0x41, 0xbd, 0x01, 0x00, 0x00, 0x00],
                field: 2,
                width: 4,
                kind: Kind::Zero,
            }, // mov r13d, 1
            Site {
                rva: 0x3e586,
                before: &[0x48, 0x81, 0xff, 0x78, 0x06, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Extent,
            }, // cmp rdi, 0x678
            Site {
                rva: 0x3e59b,
                before: &[0x4d, 0x8d, 0xbc, 0x24, 0x78, 0x06, 0x00, 0x00],
                field: 4,
                width: 4,
                kind: Kind::Extent,
            }, // lea r15, [r12 + 0x678]
            Site {
                rva: 0x3e649,
                before: &[0xba, 0x38, 0x08, 0x00, 0x00],
                field: 1,
                width: 4,
                kind: Kind::Shift,
            }, // mov edx, 0x838
            Site {
                rva: 0x3e680,
                before: &[0x41, 0xb8, 0x09, 0x00, 0x00, 0x00],
                field: 2,
                width: 4,
                kind: Kind::Count,
            }, // mov r8d, 9
            Site {
                rva: 0x3e6f7,
                before: &[0x48, 0x8b, 0xb9, 0x28, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov rdi, qword ptr [rcx + 0x828]
            Site {
                rva: 0x3e6fe,
                before: &[0x48, 0x8b, 0x99, 0x20, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov rbx, qword ptr [rcx + 0x820]
            Site {
                rva: 0x3e72c,
                before: &[0x48, 0x8b, 0xbe, 0x10, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov rdi, qword ptr [rsi + 0x810]
            Site {
                rva: 0x3e733,
                before: &[0x48, 0x8b, 0x9e, 0x08, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov rbx, qword ptr [rsi + 0x808]
            Site {
                rva: 0x3e763,
                before: &[0x4c, 0x8d, 0x93, 0x78, 0x06, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Extent,
            }, // lea r10, [rbx + 0x678]
            Site {
                rva: 0x3e7e7,
                before: &[0x48, 0x8d, 0x8e, 0x20, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // lea rcx, [rsi + 0x820]
            Site {
                rva: 0x3e7f3,
                before: &[0x48, 0x8d, 0x8e, 0x08, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // lea rcx, [rsi + 0x808]
            Site {
                rva: 0x3e7ff,
                before: &[0x48, 0x8d, 0x8e, 0xf8, 0x07, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // lea rcx, [rsi + 0x7f8]
            Site {
                rva: 0x3e818,
                before: &[0x41, 0xb8, 0x09, 0x00, 0x00, 0x00],
                field: 2,
                width: 4,
                kind: Kind::Count,
            }, // mov r8d, 9
            Site {
                rva: 0x3e8b2,
                before: &[0x48, 0x8b, 0xb7, 0xf8, 0x07, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov rsi, qword ptr [rdi + 0x7f8]
            Site {
                rva: 0x3e8d4,
                before: &[0x48, 0x8d, 0x97, 0xf8, 0x07, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // lea rdx, [rdi + 0x7f8]
            Site {
                rva: 0x3e8db,
                before: &[0x48, 0x8d, 0x8f, 0xf8, 0x07, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // lea rcx, [rdi + 0x7f8]
            Site {
                rva: 0x3e916,
                before: &[0x48, 0x8d, 0xb3, 0x78, 0x06, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Extent,
            }, // lea rsi, [rbx + 0x678]
            Site {
                rva: 0x3e91d,
                before: &[0x48, 0x89, 0x87, 0x00, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov qword ptr [rdi + 0x800], rax
            Site {
                rva: 0x3e9d0,
                before: &[0x48, 0x8d, 0x81, 0xf8, 0x07, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // lea rax, [rcx + 0x7f8]
            Site {
                rva: 0x3ee2c,
                before: &[0x48, 0x81, 0xc1, 0xf8, 0x07, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // add rcx, 0x7f8
            Site {
                rva: 0x3f13c,
                before: &[0x4c, 0x8b, 0x87, 0xf8, 0x07, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov r8, qword ptr [rdi + 0x7f8]
            Site {
                rva: 0x3f192,
                before: &[0x48, 0x8d, 0x8f, 0xf8, 0x07, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // lea rcx, [rdi + 0x7f8]
            Site {
                rva: 0x3f25a,
                before: &[0x83, 0xfb, 0x09],
                field: 2,
                width: 1,
                kind: Kind::Count,
            }, // cmp ebx, 9
            Site {
                rva: 0x3f2eb,
                before: &[0xbd, 0x09, 0x00, 0x00, 0x00],
                field: 1,
                width: 4,
                kind: Kind::Count,
            }, // mov ebp, 9
            Site {
                rva: 0x3fa65,
                before: &[0x48, 0x8d, 0x85, 0x78, 0x06, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Extent,
            }, // lea rax, [rbp + 0x678]
            Site {
                rva: 0x3fc10,
                before: &[0x48, 0x8d, 0x81, 0xf8, 0x07, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // lea rax, [rcx + 0x7f8]
            Site {
                rva: 0x3ff1e,
                before: &[0x48, 0x8b, 0xaf, 0x28, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov rbp, qword ptr [rdi + 0x828]
            Site {
                rva: 0x3ff25,
                before: &[0x48, 0x8b, 0x9f, 0x20, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov rbx, qword ptr [rdi + 0x820]
            Site {
                rva: 0x3ff4b,
                before: &[0x48, 0x8b, 0xaf, 0x10, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov rbp, qword ptr [rdi + 0x810]
            Site {
                rva: 0x3ff52,
                before: &[0x48, 0x8b, 0x9f, 0x08, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov rbx, qword ptr [rdi + 0x808]
            Site {
                rva: 0x4022d,
                before: &[0x4c, 0x8b, 0xb6, 0x28, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov r14, qword ptr [rsi + 0x828]
            Site {
                rva: 0x40234,
                before: &[0x48, 0x8b, 0x9e, 0x20, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov rbx, qword ptr [rsi + 0x820]
            Site {
                rva: 0x402b9,
                before: &[0x4c, 0x8b, 0xb6, 0x10, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov r14, qword ptr [rsi + 0x810]
            Site {
                rva: 0x402c0,
                before: &[0x48, 0x8b, 0x9e, 0x08, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov rbx, qword ptr [rsi + 0x808]
            Site {
                rva: 0x40873,
                before: &[0x4c, 0x8d, 0xb1, 0x20, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // lea r14, [rcx + 0x820]
            Site {
                rva: 0x408a5,
                before: &[0x48, 0x3b, 0x9e, 0x28, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // cmp rbx, qword ptr [rsi + 0x828]
            Site {
                rva: 0x409a1,
                before: &[0x48, 0x8b, 0x9e, 0x28, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov rbx, qword ptr [rsi + 0x828]
            Site {
                rva: 0x40a63,
                before: &[0x4c, 0x8d, 0xb1, 0x08, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // lea r14, [rcx + 0x808]
            Site {
                rva: 0x40a95,
                before: &[0x48, 0x3b, 0x9e, 0x10, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // cmp rbx, qword ptr [rsi + 0x810]
            Site {
                rva: 0x40b91,
                before: &[0x48, 0x8b, 0x9e, 0x10, 0x08, 0x00, 0x00],
                field: 3,
                width: 4,
                kind: Kind::Shift,
            }, // mov rbx, qword ptr [rsi + 0x810]
            Site {
                rva: 0x355986,
                before: &[0xb9, 0x38, 0x08, 0x00, 0x00],
                field: 1,
                width: 4,
                kind: Kind::Shift,
            }, // mov ecx, 0x838
            Site {
                rva: 0x4bf889,
                before: &[0xba, 0x38, 0x08, 0x00, 0x00],
                field: 1,
                width: 4,
                kind: Kind::Shift,
            }, // mov edx, 0x838
        ],
        redraw: 0x3eeb0,
        redraw_before: &[
            72, 137, 84, 36, 16, 72, 137, 76, 36, 8, 87, 65, 84, 72, 129, 236, 232, 0, 0, 0,
        ],
        layout: 0x2d8e70,
        layout_before: &[
            72, 137, 116, 36, 16, 87, 72, 131, 236, 64, 131, 58, 0, 72, 139, 242,
        ],
        combined: &[
            (
                0x3fa40,
                &[
                    72, 137, 92, 36, 16, 72, 137, 108, 36, 24, 72, 137, 116, 36, 32,
                ],
            ),
            (
                0x3f370,
                &[
                    72, 137, 92, 36, 16, 72, 137, 116, 36, 24, 85, 87, 65, 84, 65, 86,
                ],
            ),
            (
                0x3f9a0,
                &[
                    72, 137, 92, 36, 8, 72, 137, 116, 36, 16, 87, 72, 131, 236, 32,
                ],
            ),
            (
                0x3b6e0,
                &[
                    72, 137, 92, 36, 8, 87, 72, 131, 236, 32, 72, 139, 185, 136, 0,
                ],
            ),
            (
                0x3bb90,
                &[
                    72, 137, 92, 36, 16, 72, 137, 108, 36, 24, 72, 137, 116, 36, 32,
                ],
            ),
            (
                0x3bd40,
                &[
                    72, 137, 92, 36, 16, 72, 137, 116, 36, 24, 72, 137, 124, 36, 32,
                ],
            ),
            (
                0x2d2c80,
                &[
                    72, 137, 92, 36, 8, 72, 137, 108, 36, 16, 72, 137, 116, 36, 24, 87,
                ],
            ),
            (
                0x2ca7c0,
                &[
                    72, 137, 92, 36, 24, 72, 137, 116, 36, 32, 85, 87, 65, 86, 72, 141,
                ],
            ),
        ],
        offsets: Offsets {
            roster: 0x3d0,
            gunner_count: 0x140,
            gunner_get: 0x130,
            pool_get: 0x1c8,
            world_player: 0x708,
            ai_set: 0x3f8,
        },
    },
];
